// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: unit/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserStoreClient is the client API for UserStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserStoreClient interface {
	Get(ctx context.Context, in *Token, opts ...grpc.CallOption) (*User, error)
}

type userStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewUserStoreClient(cc grpc.ClientConnInterface) UserStoreClient {
	return &userStoreClient{cc}
}

func (c *userStoreClient) Get(ctx context.Context, in *Token, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserStoreServer is the server API for UserStore service.
// All implementations must embed UnimplementedUserStoreServer
// for forward compatibility
type UserStoreServer interface {
	Get(context.Context, *Token) (*User, error)
	mustEmbedUnimplementedUserStoreServer()
}

// UnimplementedUserStoreServer must be embedded to have forward compatible implementations.
type UnimplementedUserStoreServer struct {
}

func (UnimplementedUserStoreServer) Get(context.Context, *Token) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserStoreServer) mustEmbedUnimplementedUserStoreServer() {}

// UnsafeUserStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserStoreServer will
// result in compilation errors.
type UnsafeUserStoreServer interface {
	mustEmbedUnimplementedUserStoreServer()
}

func RegisterUserStoreServer(s grpc.ServiceRegistrar, srv UserStoreServer) {
	s.RegisterService(&UserStore_ServiceDesc, srv)
}

func _UserStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserStoreServer).Get(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// UserStore_ServiceDesc is the grpc.ServiceDesc for UserStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserStore",
	HandlerType: (*UserStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserStore_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unit/user/user.proto",
}
